### ISSUE TITLE
TS29520_Nnwdaf_EventsSubscription: invalid schemas for DispersionType, DispersionClass

### ISSUE THREAD

**Issue by std-move** [jdegre/5GC_APIs#49]
DispersionType's schema is not sound - for enum values specified in the first oneOf item (such as DVDA), both schemas match, but for oneOf to be valid, exactly 1 schema needs to match.

```
    DispersionType:
      oneOf:
      - type: string
        enum:
          - DVDA
          - TDA
          - DVDA_AND_TDA
      - type: string
```

This should probably be anyOf instead of oneOf. Analogously for DispersionClass.

The problem is still present in the latest Nwdaf OpenAPI release (17.8).
